
export const MEDIA_LIST_INITTIAL_APP_DATA_RETRIEVED = "MEDIA_LIST_INITTIAL_APP_DATA_RETRIEVED";
export const MEDIA_DATA_LIST_UPDATE = "MEDIA_DATA_LIST_UPDATE";
export const MEDIA_UPLOAD_FAILED = "MEDIA_UPLOAD_FAILED";
export const MEDIA_UPLOAD_SUCCESSFULLY = "MEDIA_UPLOAD_SUCCESSFULLY";
export const MEDIA_DOWNLOAD_FAILED = "MEDIA_DOWNLOAD_FAILED";

// NASA constant define
export const NASA_SEARCH_RESULT_RETRIEVED = "NASA_SEARCH_RESULT_RETRIEVED";

export const APP_LOADER_SHOW = "APP_LOADER_SHOW";
export const APP_LOADER_HIDE = "APP_LOADER_HIDE";