export const APP_MEDIA_RETRIEVED = "APP_MEDIA_RETRIEVED";
export const APP_INITTIAL_DATA_RETRIEVED = "APP_INITTIAL_DATA_RETRIEVED";
export const APP_UPDATE_CONTENT_LIST = "APP_UPDATE_CONTENT_LIST";
export const APP_MEDIA_UPLOAD_FAILED = "APP_MEDIA_UPLOAD_FAILED";
export const APP_MEDIA_UPLOAD_SUCCESSFULLY = "APP_MEDIA_UPLOAD_SUCCESSFULLY";
export const APP_DATA_DOWNLOAD_FAILED = "APP_DATA_DOWNLOAD_FAILED";

// NASA constant define

export const NASA_SEARCH_RESULT_RETRIEVED = "NASA_SEARCH_RESULT_RETRIEVED";